### ISSUE TITLE
Not start after import SCSS with Angular 13

### ISSUE THREAD

**Issue by Paul75** [NilavPatel/np-ui-package#6]
**Describe the bug**
Not application start when Import SCSS....

**To Reproduce**

1. Add import into main.scss file
2. do npm start
3. See error

**Expected behavior**

**Screenshots**
<code>
SassError: Can't find stylesheet to import.
   ╷
25 │ @import "~np-ui-lib/styles/default-theme";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/main.scss 25:9  root stylesheet

./src/main.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
25 │ @import "~np-ui-lib/styles/default-theme";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/main.scss 25:9  root stylesheet
    at tryRunOrWebpackError (/home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:5049:12)
    at __webpack_require__ (/home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:5006:18)
    at /home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:5077:20
    at symbolIterator (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3485:9)
    at done (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/home/pkbp512/www/VSA/vsa_client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/pkbp512/www/VSA/vsa_client/node_modules/tapable/lib/Hook.js:18:14)
    at /home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:4984:43
    at symbolIterator (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3482:9)
    at timesSync (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3463:5)
    at /home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:4949:16
    at symbolIterator (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3485:9)
    at timesSync (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3463:5)
-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
25 │ @import "~np-ui-lib/styles/default-theme";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/main.scss 25:9  root stylesheet
    at Object.<anonymous> (/home/pkbp512/www/VSA/vsa_client/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!/home/pkbp512/www/VSA/vsa_client/node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!/home/pkbp512/www/VSA/vsa_client/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!/home/pkbp512/www/VSA/vsa_client/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!/home/pkbp512/www/VSA/vsa_client/src/main.scss:1:7)
    at /home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/home/pkbp512/www/VSA/vsa_client/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/home/pkbp512/www/VSA/vsa_client/node_modules/tapable/lib/Hook.js:14:14)
    at /home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:5051:39
    at tryRunOrWebpackError (/home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:5049:12)
    at __webpack_require__ (/home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:5006:18)
    at /home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:5077:20
    at symbolIterator (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3485:9)
    at done (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/home/pkbp512/www/VSA/vsa_client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/pkbp512/www/VSA/vsa_client/node_modules/tapable/lib/Hook.js:18:14)
    at /home/pkbp512/www/VSA/vsa_client/node_modules/webpack/lib/Compilation.js:4984:43
    at symbolIterator (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:3482:9)
    at timesSync (/home/pkbp512/www/VSA/vsa_client/node_modules/neo-async/async.js:2297:7)

Generated code for /home/pkbp512/www/VSA/vsa_client/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!/home/pkbp512/www/VSA/vsa_client/node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!/home/pkbp512/www/VSA/vsa_client/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!/home/pkbp512/www/VSA/vsa_client/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!/home/pkbp512/www/VSA/vsa_client/src/main.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Can't find stylesheet to import.\n   ╷\n25 │ @import \"~np-ui-lib/styles/default-theme\";\n   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n   ╵\n  src/main.scss 25:9  root stylesheet");
</code>

**Desktop (please complete the following information):**

- OS: [e.g. iOS] : Linux
- Browser [e.g. chrome, safari] Gogoe chrome
- Version [e.g. 22] : 102

Thanks

**Comment by NilavPatel** [comment]
This is an issue from Angular 14.
https://github.com/angular/angular-cli/issues/23273
Please use workaround:

Instead of adding stylesheet with @import, add them into angular.json file as below:

"styles": [
"src/styles.scss",
"node_modules/np-ui-lib/styles/default-theme.scss"
]

**Comment by Paul75** [comment]
ERROR TypeError: Cannot read properties of undefined (reading 'subscribe')
    at NpTagsComponent.ngAfterContentInit (np-ui-lib.mjs:5575:47)
    at callHook (core.mjs:2551:1)
    at callHooks (core.mjs:2520:1)
    at executeInitAndCheckHooks (core.mjs:2471:1)
    at refreshView (core.mjs:9536:1)
    at refreshEmbeddedViews (core.mjs:10646:1)
    at refreshView (core.mjs:9519:1)
    at refreshComponent (core.mjs:10692:1)
    at refreshChildComponents (core.mjs:9291:1)
    at refreshView (core.mjs:9545:1)

**Comment by NilavPatel** [comment]
You need to pass searchResult input parameter to component. If you don't have data on init then pass empty array to subject.

**Comment by Paul75** [comment]
Hello,

I do this, add the searchResult and nothing  ....

```
<np-tags
          formControlName="htags"
          placeholder="Ajouter un htag"
          [searchResult]="[]">
        </np-tags>
```
